/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import op.io.Main;
import org.junit.Test;

import static org.junit.Assert.assertTrue;

public class ExampleTestClass {
    @Test
    public void exampleTest() {
        assertTrue(2 == Main.returnTwo());
    }
}
